openapi: 3.0.3
info:
  title: News API
  description: API for retrieving the latest news articles.
  version: 1.0.0
servers:
  - url: http://localhost:8080/news

paths:
  /everything:
    get:
      security:
        - ApiKeyAuth: []
      summary: Get the latest news articles
      parameters:
        - name: q
          in: query
          description: The search query term (e.g., 'bitcoin')
          required: true
          schema:
            type: string
            example: bitcoin
        - name: searchIn
          in: query
          description: "The fields to restrict your q search to. Possible options: title, description, content. Multiple options can be specified by separating them with a comma."
          required: false
          schema:
            type: string
            example: "title,content"
        - name: language
          in: query
          description: "The 2-letter ISO-639-1 code of the language you want to get headlines for. Possible options: ar, de, en, es, fr, hi, it, nl, no, pt, ru, sv, zh."
          required: false
          schema:
            type: string
            example: "en"
        - name: sortBy
          in: query
          description: "The order to sort the articles in. Possible options: relevancy, popularity, publishedAt."
          required: false
          schema:
            type: string
            enum:
            - relevancy
            - popularity
            - publishedAt
            example: "publishedAt"
        - name: from
          in: query
          description: "A date and optional time for the oldest article allowed. This should be in ISO 8601 format (e.g. 2025-01-20 or 2025-01-20T12:59:20)."
          required: false
          schema:
            type: string
            format: date-time
            example: "2025-01-20T12:59:20"
        - name: to
          in: query
          description: "A date and optional time for the newest article allowed. This should be in ISO 8601 format (e.g. 2025-01-20 or 2025-01-20T12:59:20)."
          required: false
          schema:
            type: string
            format: date-time
            example: "2025-01-20T12:59:20"
        - name: pageSize
          in: query
          description: The number of results to return per page
          required: false
          schema:
            type: integer
            default: 10
            example: 10
            minimum: 1
            maximum: 100
        - name: page
          in: query
          description: The page number to fetch (used with `pageSize` for pagination)
          required: false
          schema:
            type: integer
            default: 1
            example: 1
            minimum: 1
      description: Fetches the latest news articles with details like title, description, and publication date.
      operationId: getLatestNews
      responses:
        '200':
          description: A list of news articles
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  totalResults:
                    type: integer
                    example: 639
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid query parameters"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"

  /top-headlines:
    get:
      security:
        - ApiKeyAuth: []
      summary: Get the latest top headlines
      parameters:
        - name: country
          in: query
          description: "The 2-letter ISO 3166-1 code of the country you want to get headlines for. Possible options: us. Note: you can't mix this param with the sources param."
          required: false
          schema:
            type: string
            example: us
        - name: q
          in: query
          description: The search query term (e.g., 'bitcoin'). Can be used to filter headlines further.
          required: false
          schema:
            type: string
            example: bitcoin
        - name: category
          in: query
          description: "The category you want to get headlines for. Possible options: business, entertainment, general, health, science, sports, technology."
          required: false
          schema:
            type: string
            enum:
                - business
                - entertainment
                - general
                - health
                - science
                - sports
                - technology
          example: "technology"
        - name: sources
          in: query
          description: "A comma-separated string of identifiers for the news sources or blogs you want headlines from. Use the /top-headlines/sources endpoint to locate these identifiers."
          required: false
          schema:
              type: string
              example: "bbc-news,techcrunch"
        - name: pageSize
          in: query
          description: The number of results to return per page
          required: false
          schema:
            type: integer
            default: 10
            example: 10
            minimum: 1
            maximum: 100
        - name: page
          in: query
          description: The page number to fetch (used with `pageSize` for pagination).
          required: false
          schema:
            type: integer
            default: 1
            example: 1
            minimum: 1
      description: Fetches the top headlines for the specified country (or globally) with details like title, description, and publication date.
      operationId: getTopHeadlines
      responses:
        '200':
          description: A list of top news articles
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  totalResults:
                    type: integer
                    example: 639
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid query parameters"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

  schemas:
    Source:
      type: object
      properties:
        id:
          type: string
          example: "techcrunch"
        name:
          type: string
          example: "TechCrunch"

    Article:
      type: object
      properties:
        source:
          $ref: '#/components/schemas/Source'
        author:
          type: string
          example: "Anna Heim"
        title:
          type: string
          example: "Bench saved by the bell, and other last-minute deals that closed 2024 | TechCrunch"
        description:
          type: string
          example: "Welcome to Startups Weekly — your weekly recap of everything you can’t miss from the world of startups. Want it in your inbox every Friday? Sign up here."
        url:
          type: string
          example: "https://techcrunch.com/2025/01/03/bench-saved-by-the-bell-and-other-last-minute-deals-that-closed-2024/"
        urlToImage:
          type: string
          example: "https://techcrunch.com/wp-content/uploads/2019/05/GettyImages-499303888-e1586702525772.jpg?resize=1200,911"
        publishedAt:
          type: string
          format: date-time
          example: "2025-01-03T18:07:38Z"
        content:
          type: string
          example: "Welcome to Startups Weekly your weekly recap of everything you cant miss from the world of startups. Want it in your inbox every Friday?Sign up here.\r\nWelcome to 2025! The first half of the week was … [+2970 chars]"

security:
  - ApiKeyAuth: []


