openapi: 3.0.3
info:
  title: News API
  description: API for retrieving the latest news articles.
  version: 1.0.0
servers:
  - url: http://localhost:8080/news

paths:
  /everything:
    get:
      security:
        - ApiKeyAuth: []
      summary: Get the latest news articles
      parameters:
        - name: q
          in: query
          description: The search query term (e.g., 'bitcoin')
          required: true
          schema:
            type: string
            example: bitcoin
        - name: pageSize
          in: query
          description: The number of results to return per page
          required: false
          schema:
            type: integer
            default: 10
            example: 10
            minimum: 1
            maximum: 100
        - name: page
          in: query
          description: The page number to fetch (used with `pageSize` for pagination)
          required: false
          schema:
            type: integer
            default: 1
            example: 1
            minimum: 1
      description: Fetches the latest news articles with details like title, description, and publication date.
      operationId: getLatestNews
      responses:
        '200':
          description: A list of news articles
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  totalResults:
                    type: integer
                    example: 639
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid query parameters"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"

  /top-headlines:
    get:
      security:
        - ApiKeyAuth: []
      summary: Get the latest top headlines
      parameters:
        - name: country
          in: query
          description: The 2-letter ISO 3166-1 code of the country
          required: false
          schema:
            type: string
            example: us
        - name: q
          in: query
          description: The search query term (e.g., 'bitcoin'). Can be used to filter headlines further.
          required: false
          schema:
            type: string
            example: bitcoin
        - name: pageSize
          in: query
          description: The number of results to return per page
          required: false
          schema:
            type: integer
            default: 10
            example: 10
            minimum: 1
            maximum: 100
        - name: page
          in: query
          description: The page number to fetch (used with `pageSize` for pagination).
          required: false
          schema:
            type: integer
            default: 1
            example: 1
            minimum: 1
      description: Fetches the top headlines for the specified country (or globally) with details like title, description, and publication date.
      operationId: getTopHeadlines
      responses:
        '200':
          description: A list of top news articles
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  totalResults:
                    type: integer
                    example: 639
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid query parameters"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

  schemas:
    Source:
      type: object
      properties:
        id:
          type: string
          example: "techcrunch"
        name:
          type: string
          example: "TechCrunch"

    Article:
      type: object
      properties:
        source:
          $ref: '#/components/schemas/Source'
        author:
          type: string
          example: "Anna Heim"
        title:
          type: string
          example: "Bench saved by the bell, and other last-minute deals that closed 2024 | TechCrunch"
        description:
          type: string
          example: "Welcome to Startups Weekly — your weekly recap of everything you can’t miss from the world of startups. Want it in your inbox every Friday? Sign up here."
        url:
          type: string
          example: "https://techcrunch.com/2025/01/03/bench-saved-by-the-bell-and-other-last-minute-deals-that-closed-2024/"
        urlToImage:
          type: string
          example: "https://techcrunch.com/wp-content/uploads/2019/05/GettyImages-499303888-e1586702525772.jpg?resize=1200,911"
        publishedAt:
          type: string
          format: date-time
          example: "2025-01-03T18:07:38Z"
        content:
          type: string
          example: "Welcome to Startups Weekly your weekly recap of everything you cant miss from the world of startups. Want it in your inbox every Friday?Sign up here.\r\nWelcome to 2025! The first half of the week was … [+2970 chars]"

security:
  - ApiKeyAuth: []


